### ISSUE TITLE
TODO: Resource trading system

### ISSUE THREAD

**Issue by bikedawuwang** [AElfProject/aelf-block-explorer#12]
### Module
Plugin installation tips and voting use the same module
-  [x]  Resource trading wallet    2019.1.14
-  [x]  Resource currency market  2019.1.16
-  [x]  Real-time trading module  2019.1.16
-  [x]  Trading chart   2019.1.15
-  [x]  Buy and sell pop-up windows  2019.1.16

### Pages
-  [x]  Transaction history list page

### Notes
Pending....

### Module
Plugin installation tips and voting use the same module
-  [x]  Resource trading wallet
-  [x]  Resource currency market
-  [x]  Real-time trading module
-  [x]  Trading chart
-  [x]  Buy and sell pop-up windows

### Pages
-  [x]  Transaction history list page

## Test & debug
Pending....

## Deploy
 Pending....
