### ISSUE TITLE
explorer: UI TODO

### ISSUE THREAD

**Issue by hzz780** [AElfProject/aelf-block-explorer#3]
## Components

-  Search

   - [x] Search 

   - [x] Search  Banner

- [x] Header

- [x] TPS Chart

-  Information

   - [x] Block Components

   - [x] Info Container

-  [x] Blocks List

-  [x] Transactions List

-  [x]  Footer

## Pages

- [x] Home Page

- [x] Blocks list page

- [x] Block detail page

- [x] Transactions list page

- [x] Transaction detail page

- [x] Address detail page

- [ ] Applications page

- [ ] Turn to Wallet page

**Comment by hzz780** [comment]
Applications page & Turn to Wallet page -> holding

**Comment by hzz780** [comment]
See you ~~~
