### ISSUE TITLE
TODO:  Vote System

### ISSUE THREAD

**Issue by bikedawuwang** [AElfProject/aelf-block-explorer#8]
### Component
- [x] Button component ----------------------- 2018.12.20
- [x] Svg component -------------------------- 2018.12.20

### Module
- [x] Browser Plug-in Download Tips ----------  2018.12.20 -> 2018.12.21
- [x] Total voting number ---------------------  2018.12.20 -> 2018.12.21
- [x] overall number of people ----------------  2018.12.20 -> 2018.12.21
- [x] Bonus pool ------------------------------ 2018.12.20 -> 2018.12.21
- [x] Historic Income Voting Dividends -------- 2018.12.21
- [x] AElfWallet Module -----------------------  2018.12.24
- [x] Voting display ---------------------------  2018.12.24 -> 2018.12.25
- [x] Vote ------------------------------------ 2018.12.25 -> 2018.12.26
- [x] Redeem --------------------------------- 2018.12.26
- [x] My vote ---------------------------------- 2018.12.26 -> 2018.12.27
- [x] Voting record ----------------------------- 2018.12.27 

### Notes

1. Testing for multiple runs is faster than foreach

- View test cases and click [here](https://jsperf.com/test-cycle-performance/6)
- Click **Run test** to see the test results

### Data injection
- [x] Total voting number ----------------- 2019.1.2
- [x] overall number of people ----------------- 2019.1.2
- [x] Bonus pool  ----------------- 2019.1.2
- [x] Historic Income Voting Dividends   ----------------- 2019.1.3
- [x] AElfWallet Module   ----------------- 2019.1.3
- [x] Voting display   ----------------- 2019.1.4
- [x] Vote   ----------------- 2019.1.4
- [x] Redeem   ----------------- 2019.1.7
- [x] My vote   ----------------- 2019.1.8
- [x] Voting record  ----------------- 2019.1.9

### modify
Change interface logic and paging
- [x] Historic Income Voting Dividends
- [x] Voting display
- [x] My vote 
- [x] Voting record

#### TODE
1、Voting Redemption Get the error status of dividends Need to optimize

## Test & debug
- 2019.01.28
During this period, the code was sorted out, requests were changed to asynchronous, and browser plug-ins were added. Now it has reached the point where browser plug-ins can be used to operate and reduce the number of requests. Chain requests have been reduced to 59, which is 69% less than before.

## Deploy
[prepare]

**Comment by cat-walk** [comment]
Due to the contracts relative to vote has been refactor. We has to refactor the front end part of vote  correspondly. Close the issue of old schedule.
